<a href="https://colab.research.google.com/github/AstroMark11/caso_practico_en_numpy/blob/main/Ejercicio_Pr%C3%A1ctico_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio Práctico

In [1]:
import numpy as np

# Paso 1: Crear arrays con datos de ventas anuales
anios = np.array(['2012', '2013', '2014', '2015', '2016', '2017',
                  '2018', '2019', '2020', '2021', '2022', '2023'])
producto_A = np.array([1500, 2300, 8250, 9300, 7220, 4210, 2180, 4190, 9230, 2840, 8280, 8300])
producto_B = np.array([1880, 2310, 2430, 2850, 2370, 2060, 2940, 4250, 3270, 8290, 2310, 3330])
producto_C = np.array([9200, 9220, 8240, 5260, 2280, 9300, 9320, 4340, 4360, 9380, 8400, 8420])

In [2]:
# Paso 2: Transformaciones con NumPy
# Estadísticas
media_A = np.mean(producto_A)
suma_A = np.sum(producto_A)
media_B = np.mean(producto_B)
suma_B = np.sum(producto_B)
media_C = np.mean(producto_C)
suma_C = np.sum(producto_C)

print(f"Media de ventas Producto A: {media_A}")
print(f"Suma de ventas Producto A: {suma_A}")
print(f"Media de ventas Producto B: {media_B}")
print(f"Suma de ventas Producto B: {suma_B}")
print(f"Media de ventas Producto C: {media_C}")
print(f"Suma de ventas Producto C: {suma_C}")

Media de ventas Producto A: 5650.0
Suma de ventas Producto A: 67800
Media de ventas Producto B: 3190.8333333333335
Suma de ventas Producto B: 38290
Media de ventas Producto C: 7310.0
Suma de ventas Producto C: 87720


In [4]:
# Paso 3: Análisis de datos
# Calcular el total de ventas por año
total_ventas_por_anio = producto_A + producto_B + producto_C

# Calcular el promedio de ventas por producto
promedio_ventas_productos = np.array([media_A, media_B, media_C])

# Identificar el mes con mayor y menor ventas
anio_mayor_ventas = anios[np.argmax(total_ventas_por_anio)]
anio_menor_ventas = anios[np.argmin(total_ventas_por_anio)]

print("Total de ventas por año:", total_ventas_por_anio)
print("Promedio de ventas por producto:", promedio_ventas_productos)
print(f"Año con mayor ventas: {anio_mayor_ventas}")
print(f"Año con menor ventas: {anio_menor_ventas}")

Total de ventas por año: [12580 13830 18920 17410 11870 15570 14440 12780 16860 20510 18990 20050]
Promedio de ventas por producto: [5650.         3190.83333333 7310.        ]
Año con mayor ventas: 2021
Año con menor ventas: 2016


In [5]:
# Paso 4: Operaciones con NumPy
# Reshape y Transposición
ventas_matrix = np.array([producto_A, producto_B, producto_C])
ventas_reshaped = ventas_matrix.reshape(3, 4, 3)
ventas_transposed = ventas_matrix.T

print("Ventas Matrix:\n", ventas_matrix)
print("Ventas Reshaped (3, 4, 3):\n", ventas_reshaped)
print("Ventas Transposed:\n", ventas_transposed)

# Invertir arrays y aplanar matrices
ventas_inverted = ventas_matrix[:, ::-1]
ventas_flattened = ventas_matrix.flatten()

print("Ventas Invertidas:\n", ventas_inverted)
print("Ventas Aplanadas:\n", ventas_flattened)

Ventas Matrix:
 [[1500 2300 8250 9300 7220 4210 2180 4190 9230 2840 8280 8300]
 [1880 2310 2430 2850 2370 2060 2940 4250 3270 8290 2310 3330]
 [9200 9220 8240 5260 2280 9300 9320 4340 4360 9380 8400 8420]]
Ventas Reshaped (3, 4, 3):
 [[[1500 2300 8250]
  [9300 7220 4210]
  [2180 4190 9230]
  [2840 8280 8300]]

 [[1880 2310 2430]
  [2850 2370 2060]
  [2940 4250 3270]
  [8290 2310 3330]]

 [[9200 9220 8240]
  [5260 2280 9300]
  [9320 4340 4360]
  [9380 8400 8420]]]
Ventas Transposed:
 [[1500 1880 9200]
 [2300 2310 9220]
 [8250 2430 8240]
 [9300 2850 5260]
 [7220 2370 2280]
 [4210 2060 9300]
 [2180 2940 9320]
 [4190 4250 4340]
 [9230 3270 4360]
 [2840 8290 9380]
 [8280 2310 8400]
 [8300 3330 8420]]
Ventas Invertidas:
 [[8300 8280 2840 9230 4190 2180 4210 7220 9300 8250 2300 1500]
 [3330 2310 8290 3270 4250 2940 2060 2370 2850 2430 2310 1880]
 [8420 8400 9380 4360 4340 9320 9300 2280 5260 8240 9220 9200]]
Ventas Aplanadas:
 [1500 2300 8250 9300 7220 4210 2180 4190 9230 2840 8280 8300 1880 

In [6]:
# Paso 5: Análisis de elementos y sus conteos
unique_ventas, counts_ventas = np.unique(ventas_flattened, return_counts=True)
print("Elementos únicos en las ventas:", unique_ventas)
print("Conteos de elementos únicos en las ventas:", counts_ventas)

Elementos únicos en las ventas: [1500 1880 2060 2180 2280 2300 2310 2370 2430 2840 2850 2940 3270 3330
 4190 4210 4250 4340 4360 5260 7220 8240 8250 8280 8290 8300 8400 8420
 9200 9220 9230 9300 9320 9380]
Conteos de elementos únicos en las ventas: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1]


In [10]:
# Paso 6: Indexación y slicing
# Seleccionar ventas de los primeros tres años
ventas_tres_primeros_anios = ventas_matrix[:, :3]
print("Ventas de los primeros tres años:\n", ventas_tres_primeros_anios)

# Indexación booleana para seleccionar meses con ventas totales superiores a 12000
anios_altas_ventas = anios[total_ventas_por_anio > 12000]
ventas_altas = total_ventas_por_anio[total_ventas_por_anio > 12000]
print("Anios con ventas totales superiores a 12000:", anios_altas_ventas)
print("Ventas totales superiores a 12000:", ventas_altas)

# Selección avanzada
indices = [0, 2, 4, 6, 8, 10]
ventas_indices_seleccionados = ventas_matrix[:, indices]
print("Ventas en anios seleccionados:\n", ventas_indices_seleccionados)

Ventas de los primeros tres años:
 [[1500 2300 8250]
 [1880 2310 2430]
 [9200 9220 8240]]
Anios con ventas totales superiores a 12000: ['2012' '2013' '2014' '2015' '2017' '2018' '2019' '2020' '2021' '2022'
 '2023']
Ventas totales superiores a 12000: [12580 13830 18920 17410 15570 14440 12780 16860 20510 18990 20050]
Ventas en anios seleccionados:
 [[1500 8250 7220 2180 9230 8280]
 [1880 2430 2370 2940 3270 2310]
 [9200 8240 2280 9320 4360 8400]]
